Repository wecode-bootcamp-korea/43-1st-Sipscent-frontend, pull requests merged in 2023-03, with the labels that each got.

#1 FIX : package.json 재설치
  package-lock.json
  package.json
Labels: 완료

#4 [43기 권유정] Add : Cart 컴포넌트 레이아웃 구현
  .stylelintrc.js
  src/components/Cart/Cart.js
  src/components/Cart/Cart.scss
Labels: 멘토 리뷰 요청

#5 [43기 권유정] Add : filter 컴포넌트 레이아웃 구현 완료
  src/components/Filter/Filter.js
  src/components/Filter/Filter.scss
Labels: 멘토 리뷰 요청

#11 [43기 권유정] Add : footer 컴포넌트 구현 완료
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterData.js
Labels: 멘토 리뷰 요청

#3 [43기 유정인] ADD: 메인 레이아웃 구현 완료, MODIFY: 메인 캐러셀 구현 완료
  .stylelintrc.js
  package-lock.json
  public/images/Main/Main.png
  public/images/Main/MainCitrus.jpg
  public/images/Main/MainFloral.jpg
  public/images/Main/MainFruity.jpg
  public/images/Main/MainGreen.jpg
  public/images/Main/MainHerbal.jpg
  public/images/Main/MainSpicy.jpg
  public/images/Nav/로고 이미지.png
  src/components/Nav/Nav.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/mainCategoryData.js
  src/pages/Order/Order.js
Labels: 수정 요청

#13 [43기 권유정] Add: 상수 데이터 price range 수정
  src/components/Filter/Filter.js
Labels: 멘토 리뷰 요청

#2 [43기 권유정] Add : conflict 해결
  public/data/cupListData.json
  public/data/teaListData.json
  public/images/Nav/로고 이미지.png
  public/images/ProductDetail/k8-eacOgTpdAJc-unsplash.jpg
  public/images/ProductDetail/morgan-sessions-k5zv-Hv4Kpc-unsplash.jpg
  public/index.html
  src/Router.js
  src/components/Cart/Cart.js
  src/components/Cart/Cart.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/ProductWrap.js
  src/pages/ProductList/ProductWrap.scss
  src/styles/common.scss
Labels: Conflict 해결 완료

#12 [43기 권유정] Add : 리뷰 사항 수정 완료
  src/components/Cart/Cart.js
  src/components/Cart/Cart.scss
  src/components/CartProductsListItem/CartProductsListItem.js
  src/components/CartProductsListItem/CartProductsListItem.scss
Labels: Conflict 해결 완료

#9 [43기 김민경]ADD:로그인 기능 구현
  package-lock.json
  public/index.html
  src/Router.js
  src/assets/Main/Main.js
  src/components/Login/Login.js
  src/components/Login/Login.scss
  src/config.js
  src/styles/common.scss
Labels: Conflict 해결 완료

#8 [43기 권유정] Add: product detail data 경로 수정
  public/images/ProductDetail/라일락차.jpg
  src/Router.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductWrap.js
Labels: 멘토 리뷰 요청, Conflict 해결 완료

#10 [43기 김민경]ADD : 회원가입 기능 구현
  src/pages/Signup/Checkbox.js
  src/pages/Signup/Checkbox.scss
  src/pages/Signup/SIGN_UP_INPUT_DATA.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: Conflict 해결 완료

#15 [43기 권유정] Add: cart 컴포넌트 fetch 적용, 모달창으로 변경
  src/components/Cart/Cart.js
  src/components/Cart/Cart.scss
  src/components/CartProductsListItem/CartProductsListItem.js
  src/components/CartProductsListItem/CartProductsListItem.scss
  src/config.js
Labels: Conflict 해결 완료

#18 [43기 유정인] MODIFY: router(order -> orders)로 변경, alert문구 변경
  src/Router.js
  src/pages/Order/Order.js
Labels: Conflict 해결 완료

#23 [43기 권유정] Add: product detail page에서 포인트 부족시 alert창 뜨도록
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청

#22 [43기 권유정] Add : cart page에서 포인트 초과시 alert창 뜨도록
  src/components/Cart/Cart.js
Labels: 멘토 리뷰 요청

#19 [43기 유정인] ADD: 정렬 및 필터 기능 추가
  src/components/Filter/Filter.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/ProductList/ProductList.js
Labels: 멘토 리뷰 요청

#20 [43기 유정인] ADD: 주문확인페이지(orderView)생성, router.js에 orderView route추가,MODIFY: order…
  src/Router.js
  src/pages/Order/Order.js
  src/pages/Order/OrderView.js
  src/pages/Order/OrderView.scss
Labels: Conflict 해결 완료

#21 [43기 권유정] Add : filter 기능 구현
  src/components/Filter/Filter.js
Labels: Conflict 해결 완료

#16 [43기 권유정] Add: 정렬 기능 완료
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/ScrollToTop.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductWrap.js
Labels: Conflict 해결 완료
